### ISSUE TITLE
Logo animation - first pass

### ISSUE THREAD

**Issue by psobrakseaton** [hypergraph-xyz/design#6]
@psobrakseaton and @chartgerink talked about this as a form of a loading animation and for the logo display in the main view.

The main idea was to fan out the layers of the Hypergraph logo, and fan them back in.

**Comment by jameslibscie** [comment]
What do we want this for? Making thing sleeker in the desktop app / website / etc.?

**Comment by chartgerink** [comment]
AFAIK @psobrakseaton and I talked about this as a form of a loading aninmation and for the logo display in the main view as a gimmick first, later a feature.

The main idea was to fan out the layers of the Hypergraph logo, and fan them back in. Maybe we should flesh out the issues a bit for reference and contextualisation?

**Comment by juliangruber** [comment]
If something isn't too much work and rewarding, IMO it's ok to do things that don't serve a direct purpose
