### ISSUE TITLE
On-Boarding View/Flow

### ISSUE THREAD

**Issue by psobrakseaton** [hypergraph-xyz/design#8]
Create a step-by-step of the on-boarding/profile creation process

**Comment by juliangruber** [comment]
Why were all of these closed?

**Comment by juliangruber** [comment]
..and are still in the To do column? Just curious

**Comment by jameslibscie** [comment]
Good question. I've closed these issues after discussing with Patch because they will be replaced by new issues in the desktop repo. This repo will be used for branding and product-specific design work goes into each respective repo. I've also closed the design board to prevent confusion :)

**Comment by juliangruber** [comment]
Ok thanks, I understand. In the future a quick comment can help prevent confusion

**Comment by jameslibscie** [comment]
Definitely will! Made an incorrect assumption that Patch would be the only one looking here.
